# Generated by Django 4.1.7 on 2023-02-24 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('store', '0002_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PAD', 'پرداخت شده'), ('PRP', 'در حال آماده سازی'), ('PST', 'در حال ارسال'), ('DLV', 'تحویل داده شده')], default='PAD', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=700)),
                ('post_code', models.IntegerField()),
                ('shipping_price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='address', to='utils.city')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='order.order')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='address', to='utils.state')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=70)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('qty', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product')),
            ],
        ),
    ]
